import { expect, test } from '@playwright/test';
import { hashFromQuery } from '@tinacms/bridge/metadata';
// ponytail: query docs imported from the repo's own generated client so the
// envelope key is byte-identical to what requestWithMetadata hashes at
// runtime (not a hand-shaped guess). Regenerated by `tinacms build` in CI
// before e2e, so this import is safe wherever generation runs.
import {
  AboutDocument,
  HomepageDocument,
} from '../../../../tina/__generated__/types.js';

/**
 * TinaCMS visual editing protocol — proves the true bridge contract:
 * - TinaIsland wrappers present with data-tina-island attributes
 * - Inline in-iframe bootstrap present (no external bridge src in static HTML)
 * - Island route is NOT an open mutation endpoint: GET is rejected (405),
 *   POST without the Tina preview content-type is rejected (404).
 * Field mapping itself is proven by scripts/check-tina-field-parity.mjs
 * (source-level, deterministic, no browser required).
 */

test('TinaIsland wrappers present in DOM', async ({ page }) => {
  await page.goto('/');
  const islandWrappers = await page.locator('[data-tina-island]');
  const count = await islandWrappers.count();
  expect(count).toBeGreaterThanOrEqual(2);
});

test('island wrappers match registry names', async ({ page }) => {
  await page.goto('/');
  for (const name of ['hero', 'aboutSection', 'whyChooseUs']) {
    const marker = await page.locator(
      `[data-tina-island="/tina-island/${name}"]`,
    );
    await expect(marker, `island wrapper for ${name}`).toHaveCount(1);
  }
});

test('tina-island route rejects GET (not an open endpoint)', async ({
  page,
}) => {
  const response = await page.request.get('/tina-island/hero');
  expect([404, 405]).toContain(response.status());
});

test('tina-island route rejects POST without preview content-type', async ({
  page,
}) => {
  const response = await page.request.post('/tina-island/hero', {
    data: { headline: 'Test Headline' },
  });
  expect(response.status()).toBe(404);
});

test('tina-island rejects unknown island names', async ({ page }) => {
  const response = await page.request.post(
    '/tina-island/nonexistent-collection',
    {
      data: { headline: 'Test' },
    },
  );
  // Rejected at the boundary (404 missing preview content-type) — never a mutation.
  expect([404, 405]).toContain(response.status());
});

// ---------------------------------------------------------------------------
// B2 island-route gate pins (task-B1-spec §6). Public-by-design preview
// renderer: the gate lives upstream in rejectIfUnsafe; these tests pin the
// boundary (403/404/405), the stored-fallback and draft-echo semantics, and
// the one repo-owned sink fix (CTA href hygiene, R-CTA-01).
// ---------------------------------------------------------------------------

const PREVIEW_CT = 'application/x-tina-preview+json';

// Envelope keys derived from installed source, not hand-shaped:
// requestWithMetadata (@tinacms/astro/dist/data.js) looks up the overlay at
// hashFromQuery (@tinacms/bridge/dist/metadata.js) of
// JSON.stringify({ query, variables }). When the TinaCloud fetch fails (dev
// without creds: 401 -> result null), the server hashes
// { query: '', variables: {} } instead — so both keys are sent and the suite
// holds with and without TinaCloud credentials.
const homeId = hashFromQuery(
  JSON.stringify({
    query: HomepageDocument,
    variables: { relativePath: 'homepage.json' },
  }),
);
const aboutId = hashFromQuery(
  JSON.stringify({
    query: AboutDocument,
    variables: { relativePath: 'about.json' },
  }),
);
const emptyId = hashFromQuery(JSON.stringify({ query: '', variables: {} }));

function heroOverlay(doc: Record<string, unknown>) {
  return { [homeId]: { homepage: doc }, [emptyId]: { homepage: doc } };
}

function aboutOverlay(doc: Record<string, unknown>) {
  return { [aboutId]: { about: doc }, [emptyId]: { about: doc } };
}

function fullHomepageDoc(overrides: Record<string, unknown>) {
  return {
    eyebrow: 'UK Bangla Tigers Cricket Club',
    headline: 'R-GATE-HEADLINE',
    tagline: 'United by Passion. Driven by Cricket.',
    primaryCtaLabel: 'Join the Club',
    primaryCtaLink: '/join/',
    heroImage: '/media/team-huddle.webp',
    ...overrides,
  };
}

// javascript: hrefs after up-to-3-rounds percent-decoding (mirrors the
// canonicalization in src/lib/allowed-urls.ts), case-insensitive.
function jsHrefs(html: string): string[] {
  const hits: string[] = [];
  for (const m of html.matchAll(/href="([^"]*)"/g)) {
    let decoded = m[1];
    for (let i = 0; i < 3; i++) {
      try {
        const next = decodeURIComponent(decoded);
        if (next === decoded) break;
        decoded = next;
      } catch {
        break;
      }
    }
    if (decoded.toLowerCase().startsWith('javascript:')) hits.push(m[1]);
  }
  return hits;
}

// CI serves dist/client/ statically (serve-static.mjs): the on-demand Worker
// route 404s there. Dev (`pnpm dev`) + production serve it live (T3 matrix +
// smoke island check own that coverage). Probe once per worker; skip where absent.
let islandRouteAlive: boolean | null = null;
async function requireIslandRoute(
  request: import('@playwright/test').APIRequestContext,
) {
  if (islandRouteAlive === null) {
    const probe = await request
      .post('/tina-island/hero', {
        headers: { 'content-type': PREVIEW_CT },
        data: {},
      })
      .catch(() => null);
    islandRouteAlive = probe !== null && probe.status() !== 404;
  }
  test.skip(
    !islandRouteAlive,
    'island route absent on static preview server; covered live by T3 matrix + smoke',
  );
}

test('R-GATE-01 cross-site POST is rejected (403)', async ({ page }) => {
  await requireIslandRoute(page.request);
  const response = await page.request.post('/tina-island/hero', {
    headers: {
      'content-type': PREVIEW_CT,
      'sec-fetch-site': 'cross-site',
    },
    data: {},
  });
  expect(response.status()).toBe(403);
});

test('R-GATE-02 empty overlay falls back to stored content', async ({
  page,
}) => {
  await requireIslandRoute(page.request);
  const response = await page.request.post('/tina-island/hero', {
    headers: { 'content-type': PREVIEW_CT },
    data: {},
  });
  expect(response.status()).toBe(200);
  const body = await response.text();
  expect(body).toContain('data-tina-island="/tina-island/hero"');
  expect(body).toContain('UK Bangla Tigers Cricket Club');
  expect(body.includes('[object Object]')).toBe(false);
});

test('R-GATE-03 keyed overlay echoes draft headline', async ({ page }) => {
  await requireIslandRoute(page.request);
  const response = await page.request.post('/tina-island/hero', {
    headers: { 'content-type': PREVIEW_CT },
    data: heroOverlay({
      tagline: 'United by Passion. Driven by Cricket.',
      headline: 'R-GATE-03-ECHO',
      primaryCtaLabel: 'Join the Club',
      primaryCtaLink: '/join',
    }),
  });
  expect(response.status()).toBe(200);
  const body = await response.text();
  expect(body).toContain('data-tina-island="/tina-island/hero"');
  expect(body).toContain('R-GATE-03-ECHO');
});

for (const variant of [
  'javascript:alert(1)',
  'JaVaScRiPt:alert(1)',
  '%6aavascript:alert(1)',
]) {
  test(`R-CTA-01 overlay CTA href variant never renders executable (${variant})`, async ({
    page,
  }) => {
    await requireIslandRoute(page.request);
    const response = await page.request.post('/tina-island/hero', {
      headers: { 'content-type': PREVIEW_CT },
      data: heroOverlay(fullHomepageDoc({ primaryCtaLink: variant })),
    });
    expect(response.status()).toBe(200);
    const body = await response.text();
    expect(jsHrefs(body)).toEqual([]);
  });
}

test('R-IMG-01 overlay heroImage javascript: falls back', async ({ page }) => {
  await requireIslandRoute(page.request);
  const response = await page.request.post('/tina-island/hero', {
    headers: { 'content-type': PREVIEW_CT },
    data: heroOverlay(fullHomepageDoc({ heroImage: 'javascript:alert(1)' })),
  });
  expect(response.status()).toBe(200);
  const body = await response.text();
  expect(body).toContain('/media/team-huddle.webp');
  expect(body.includes('src="javascript:')).toBe(false);
});

test('R-TRUTH-01 overlay cannot move code-pinned stats/roster', async ({
  page,
}) => {
  await requireIslandRoute(page.request);
  const leadership = await page.request.post('/tina-island/aboutLeadership', {
    headers: { 'content-type': PREVIEW_CT },
    data: aboutOverlay({
      heroSubline: 'R-TRUTH-SUBLINE',
      leadershipIntro: 'R-TRUTH-INTRO',
      leaders: [{ name: 'EVIL', role: 'EVIL' }],
    }),
  });
  expect(leadership.status()).toBe(200);
  const leadershipBody = await leadership.text();
  expect(leadershipBody).toContain('Mohammad Chowdhury');
  expect(leadershipBody).toContain('R-TRUTH-INTRO');
  expect(leadershipBody.includes('EVIL')).toBe(false);

  const story = await page.request.post('/tina-island/aboutStory', {
    headers: { 'content-type': PREVIEW_CT },
    data: aboutOverlay({
      heroSubline: 'R-TRUTH-SUBLINE',
      stats: { players: '9999' },
      founded: '1999',
    }),
  });
  expect(story.status()).toBe(200);
  const storyBody = await story.text();
  expect(storyBody).toContain('50+');
  expect(storyBody).toContain('2020');
  expect(storyBody.includes('9999')).toBe(false);
  expect(storyBody.includes('1999')).toBe(false);
});
